### ISSUE TITLE
Release for Xcode 11

### ISSUE THREAD

**Issue by jeroenleenarts** [usabilla/usabilla-u4a-ios-swift-sdk#152]
Apple released the production version of Xcode 11 2 days ago. Where's the release SDK by Usabilla.

In our project we are now considering capturing the network traffic from the SDK and build our own screens and calls to the Usabilla endpoints to get rid of the only compiled third party dependency we have. Usabilla is the component that causes us more headache than benefit at this point, every single time an update is released by Apple.

What is so special about the contents of the SDK that it can't be released as an open source component?

**Comment by keshcreations** [comment]
Hi @jeroenleenarts, 

Our team is currently finalizing the new version of our SDK. Once this is released, we will update you regarding this as well. For reference, we start working on new versions of our SDK when the final version of XCode is released. We do not create new versions of our SDK based on Beta versions to ensure that the SDK that we're releasing is compatible with the final version.

The process of making our SDK open source is actually something we're looking into right now. If this is is something that could be interesting for us, we will definitely put it on our roadmap.

**Comment by rudchenkos** [comment]
Hi @keshcreations 

Thanks for the update.
Do you have any ETA for the Xcode 11 compatible release?

**Comment by rajatanantharam** [comment]
Version v6.4.0-Xcode-11 with XCode 11 does not compile the project. I am seeing this error `Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler `. At this point, the usabilla SDK is holding us back from using the latest (stable) version of XCode. 

When can we expect a fix for this?

Thanks

**Comment by torkvell** [comment]
Hi @rajatanantharam ,

Have you made sure you're pointing to the latest release in your Pod file? You have to specify it like this:

`pod ‘Usabilla’, :git => ’https://github.com/usabilla/usabilla-u4a-ios-swift-sdk', :tag => ‘v6.4.0-Xcode-11’`

I hope this helps. Please let me know how it goes.

**Comment by jimmyjansen93** [comment]
Hi @torkvell It doesnt make much sense to use a tag for the `podfile` where we can simply specify a version right? 

Why not just make a 6.4.1 release that is working on xcode 11?

**Comment by torkvell** [comment]
Hi @jimmyjansen93,

In our next release we'll make sure to update the cocoapods, for now please use the provided method as outlined above. 

If there is anything else, please let me know.

**Comment by jimmyjansen93** [comment]
When is this release due? 

Again, like many others, we don't  like to have a tag in our podfile. We freeze our versions there and using a tag does not help with that policy.

**Comment by torkvell** [comment]
Hi @jimmyjansen93 ,

Giving a time frame on this is quite hard as it all depends on how long building the new features will take. Pointing to the correct release in your podfile is the only way you can make it work for now.

**Comment by jimmyjansen93** [comment]
@torkvell that doesnt answer my question? This is clearly **forcing** clients to have bad practice. 

Why not just do a simple github release with these new binaries that allow us to use a clear version? This will save you a lot of hassle debating on github and will make a lot of people happy.

**Comment by torkvell** [comment]
Hi @jimmyjansen93 ,

I'm sorry to hear you take my workaround in that way. Next time we release a new version we shall upgrade the cocoapods as well, even if the changes are only Xcode related.

**Comment by jimmyjansen93** [comment]
Your workaround is a hack. How can I trust you to not mess up the tag?

Never mind this, I will let my manager contact yours 👍

**Comment by andriyslyusar** [comment]
Any updated today?

**Comment by torkvell** [comment]
Hi all,

Thank you all for your patience on this. 

We'll update the cocoapods next week, including two other minor fixes to the SDK. In the interim, please make use of the workaround provided above.

If there is anything else, please let me know.

**Comment by rajatanantharam** [comment]
@torkvell  : Thanks for prioritising this issue 👍

**Comment by qasimmajeed** [comment]
Error : Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler:
i need the usabilla with swift 4.2 build with Xcode 11

**Comment by torkvell** [comment]
Hi @qasimmajeed,

Our latest release has been built with Xcode11 which supports the 5.1 compiler. In your podfile, you have to specify this:
`pod ‘Usabilla’, :git => ’https://github.com/usabilla/usabilla-u4a-ios-swift-sdk', :tag => ‘v6.4.0-Xcode-11`

Next week, we'll make sure to update the cocoapods accordingly

**Comment by qasimmajeed** [comment]
Hi @torkvell 
 Is that release supports **swift 4.2** ? because i need this release with this swift version

**Comment by torkvell** [comment]
Hi @qasimmajeed ,

The release we have for Swift 4.2 is the one built for Xcode 10: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/blob/Xcode-10/Usabilla.framework/Headers/Usabilla-Swift.h

I hope this helps. Let me know if there is anything else.

**Comment by qasimmajeed** [comment]
Hi @torkvell 
By using the above suggestion i am facing this problem again.I attach the screen shot.
<img width="530" alt="Screen Shot 2019-10-08 at 10 27 29 PM" src="https://user-images.githubusercontent.com/12518819/66422700-2fe40500-ea1b-11e9-877a-187fd84a25d4.png">

**Comment by michaelclearscore** [comment]
Every single swift release we are blocked from upgrading by Usabilla. How hard is it to recompile with 5.1 and push new version of pod. Better yet open source it so this issue goes away. I cant wait till my company abandons Usabilla entirely. How are you not embarrassed devs ?

**Comment by qasimmajeed** [comment]
@michaelclearscore  you are right this is only dependency in my project which is blocking me on every update.It must be open source.

**Comment by torkvell** [comment]
Hi everyone,

Thank you all for your patience on this. We have now released a new version which is built with Xcode 11.1: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases. Cocoapods now point to Xcode 11.1 as well. 

I would like to apologize for any inconvenience in relation to this. If Apple releases a new Xcode version that breaks the cocoapods we will bump the SDK and release a new cocoapod with this next time.

If there is anything else, please let us know.

**Comment by qasimmajeed** [comment]
@torkvell after updating the pods with the latest release i am still facing the following problem

<img width="466" alt="Screen Shot 2019-10-10 at 1 14 40 PM" src="https://user-images.githubusercontent.com/12518819/66555670-19939180-eb60-11e9-887a-431f06464a0b.png">
