### ISSUE TITLE
CocoaPods compiled with Swift 5.1

### ISSUE THREAD

**Issue by joamafer** [usabilla/usabilla-u4a-ios-swift-sdk#163]
Using your workaround of pointing to this within the Podfile:

```
pod 'Usabilla', :git => 'https://github.com/usabilla/usabilla-u4a-ios-swift-sdk', :tag => 'v6.4.0-Xcode-11'
```

Whenever we run pod install it brings a dsym compiled with Swift 5.0.1 when we need it compiled with Swift 5.1. This is the only pod failing and we need to have it fixed ASAP as we need to release on Thursday. The project won't compile unless we delete the generated dsym within the build phase. We need a proper fix!

**Comment by michaelclearscore** [comment]
Every single swift release we are blocked from upgrading by Usabilla. How hard is it to recompile with 5.1 and push new version of pod. Better yet open source it so this issue goes away. I cant wait till my company abandons Usabilla entirely.

**Comment by torkvell** [comment]
Hi everyone,

Thank you all for your patience on this. We have now released a new version which is built with Xcode 11.1: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases. Cocoapods now point to Xcode 11.1 as well.

I would like to apologize for any inconvenience in relation to this. If Apple releases a new Xcode version that breaks the cocoapods we will bump the SDK and release a new cocoapod with this next time.

If there is anything else, please let us know.

**Comment by joamafer** [comment]
@torkvell still the dsym files seem wrong. I can't compile with the dsym files generated from Usabilla 6.4.1.

**Comment by joamafer** [comment]
This should be reopened as it doesn't fix the generated dsym files within the build phase when running "pod install".
