### ISSUE TITLE
6.4.0-Xcode-11 does not build with XCode 11.2

### ISSUE THREAD

**Issue by iwllyu** [usabilla/usabilla-u4a-ios-swift-sdk#169]
I see there's a tag for `v6.4.2-Xcode-11.2-beta2`

but please take a look at https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler

>Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

>I'm used to swift compiler mismatches, and I'm aware I can just recompile RxSwift using Xcode 11.2 and carry on, but the headline feature of Swift 5.1 was module stability.

>I was under the impression that now that we have module stability, frameworks won't need to keep getting recompiled with every new Xcode release, yet this is clearly not the case.

reading the answer states:

> You need to set the Build Libraries for Distribution option to Yes in your framework's build settings, otherwise the swift compiler doesn't generate the neccessary .swiftinterface files which are the key to future compilers being able to load your old library.

>This ends up in your project.pbxproj file as:

>**BUILD_LIBRARY_FOR_DISTRIBUTION = YES;**
After setting this flag, a framework I compiled using Xcode 11.0 (swift 5.1) was able to be compiled with Xcode 11.2 (swift 5.1.2) and everything appears to be working correctly.

Please set the `BUILD_LIBRARY_FOR_DISTRIBUTION` flag in future releases if it hasn't been set already, thanks!

**Comment by Saik0s** [comment]
Are there any estimations when this problem is going to be addressed? Usabilla SDK is again blocking for our product to use the latest Swift version.

**Comment by jnbt** [comment]
In the meanwhile I was successful on Xcode 11.2 by using the following line in the Podfile:

```
pod 'Usabilla', git: 'https://github.com/usabilla/usabilla-u4a-ios-swift-sdk.git', tag: 'v6.4.2-Xcode-11.2-beta2'
```

**Comment by mthormann-dhi** [comment]
Agree with @iwllyu and @Saik0s.  It's not helping efforts to keep using Usabilla as a product.  This problem has been solved and we need it implemented.

**Comment by farhad-ris** [comment]
OK, Turns out if you watch the WWDC video, they explain it: https://developer.apple.com/videos/play/wwdc2019/416/

You need to set the Build Libraries for Distribution option to Yes in your framework's build settings, otherwise the swift compiler doesn't generate the neccessary .swiftinterface files which are the key to future compilers being able to load your old library.

This ends up in your project.pbxproj file as:

BUILD_LIBRARY_FOR_DISTRIBUTION = YES;
After setting this flag, a framework I compiled using Xcode 11.0 (swift 5.1) was able to be compiled with Xcode 11.2 (swift 5.1.2) and everything appears to be working correctly.

Hopefully this question/answer will serve as a useful reference for everyone who hasn't watched all the WWDC videos

**Comment by torkvell** [comment]
Hi all,

Thanks for taking the time to consider how we can improve our product. I think you make a great case with your suggestion. While I’m afraid I can’t make any promises, I am going to share your thoughts with our team here for consideration in future developments. 

To fix the issue with the compilation mismatch, please follow these steps:

Download the latest framework file from the beta release:
![2019-11-08 at 11 28](https://user-images.githubusercontent.com/40064170/68469666-e570c680-021a-11ea-94cd-d039d12d97b0.png)

Replace your local framework file with the one downloaded:
![2019-11-08 at 11 30](https://user-images.githubusercontent.com/40064170/68469831-3ed8f580-021b-11ea-9cb3-58807bc89912.png)

I hope this helps. If there is anything else I can assist on, please let me know.

**Comment by RayAnd** [comment]
Hello, when this steps might help with local development it's not useful for Build Pipeline and CI systems...

Is it possible to fix Carthage integrations, since you seems have binary already on hand?

**Comment by torkvell** [comment]
Hi @RayAnd ,

With Carthage you can point to this link: ```"6.4.2": "https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/download/v6.4.2-Xcode-11.2-beta2/Carthage.framework.zip"
```

**Comment by RayAnd** [comment]
Hello,

For Carthage it should be .json file for this binary link like:
`binary "https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/Usabilla.json"`

Direct link to zip file would not work.

**Comment by Saik0s** [comment]
> Hi all,
> 
> Thanks for taking the time to consider how we can improve our product. I think you make a great case with your suggestion. While I’m afraid I can’t make any promises, I am going to share your thoughts with our team here for consideration in future developments.
> 
> To fix the issue with the compilation mismatch, please follow these steps:
> 
> Download the latest framework file from the beta release:
> ![2019-11-08 at 11 28](https://user-images.githubusercontent.com/40064170/68469666-e570c680-021a-11ea-94cd-d039d12d97b0.png)
> 
> Replace your local framework file with the one downloaded:
> ![2019-11-08 at 11 30](https://user-images.githubusercontent.com/40064170/68469831-3ed8f580-021b-11ea-9cb3-58807bc89912.png)
> 
> I hope this helps. If there is anything else I can assist on, please let me know.

While this can be a temporary solution, we can not release an app with a dependency build using beta tools.

**Comment by torkvell** [comment]
Hi everyone,

Great news! In our next release, we'll also set the `BUILD_LIBRARY_FOR_DISTRIBUTION` flag, as suggested. I hope this helps.

**Comment by torkvell** [comment]
@RayAnd ,

For Carthage: `https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/blob/Xcode-11.2-beta2/Usabilla.json`

**Comment by RayAnd** [comment]
This link not working, as Carthage throwing following error:

```
Unable to parse binary-only framework JSON at https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/blob/Xcode-11.2-beta2/Usabilla.json due to error: invalid JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 6." UserInfo={NSDebugDescription=Invalid value around character 6.})))
```

**Comment by dogahe** [comment]
We have the same issue as RayAnd. We use many frameworks and the only framework that always breaks our app with every updated of Xcode and Swift is Usabilla.

**Comment by koenpunt** [comment]
When can we expect a non-beta release?

**Comment by torkvell** [comment]
Hi @koenpunt ,

The next release will be done early next week.

**Comment by torkvell** [comment]
Hi all,

We've now released 6.4.3 with module format stability. This should resolve issues with compiler issues from Xcode 11 and forward. 

If there is anything else, please let us know.

**Comment by dogahe** [comment]
@torkvell 

I still have the issue:

*** Downloading binary-only framework Usabilla at "https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/master/Usabilla.json"
*** xcodebuild output can be found in /var/folders/11/tjwvq_yx4mj042kv46mxz1wh0000gn/T/carthage-xcodebuild.6Y0GXC.log
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9).
