### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by joamafer** [usabilla/usabilla-u4a-ios-swift-sdk#172]
Again, the same issue. When will you have a fix for this?

**Comment by joamafer** [comment]
@torkvell We had to downgrade to Xcode 11.1 from 11.2.1 just because of this framework. The fact we have problems with Usabilla on every Xcode version is becoming unacceptable...

**Comment by torkvell** [comment]
Hi @joamafer ,

Thanks for reaching out on this. I'm more than happy to clarify this for you. This issue has already been addressed here: [https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/169](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/169). In other words: We'll publish a new release tomorrow which shall take care of compilation versioning issues. 

I hope this helps. If there is anything else, please let me know.

**Comment by torkvell** [comment]
Hi all,

We've now released 6.4.3 with module format stability. This should resolve issues with compiler issues from Xcode 11 and forward. 

If there is anything else, please let us know.

**Comment by RayAnd** [comment]
Hi @torkvell with release 6.4.3 we still see issue in Xcode 11.2.1.

```
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9).
```

We use Carthage v0.34.0. and suggested method of importing framework as `binary "https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/master/Usabilla.json"`

Any resolution for Carthage? Did you actually tested this way of importing framework for latest Xcode?

Best,
Andrey

**Comment by dogahe** [comment]
Hi @torkvell, I have the exact same issue as RayAnd.

**Comment by torkvell** [comment]
Hi @RayAnd and @dogahe, 

Thank you for your patience on this. First of all I would like to apologize for any inconvenience caused by this Swift compiler versioning issue. 

We implemented a change in our SDK for modular stability which shall make sure that our SDK can be compiled with any Xcode versions from Xcode 11 and up. This has proven to be successful for Cocoapods. However, this unfortunately, didn't work for Carthage. We also did some tests on this before the release was published, but it seems to still be a compilation issue for some Xcode versions in combination with Carthage. We're now investigating how we can make this successful for Carthage as well. 

As a temporary fix we'll release a new Carthage file which is built with the latest Xcode version. You can expect to have this available within the next 24 hours. 

In the interim, please let us know if there is anything else we can assist with.

**Comment by joamafer** [comment]
"This has proven to be successful for Cocoapods."

Well, we still have issues with CocoaPods as I mentioned in the other issue. Now it's the duplicated dsym issue. This time we had 2 options after spending one day: Come back to Xcode 11.1, or downgrade Cocoapods.

Honestly, paying for a framework and receive things like "I can't make any promise" about fixing issues, or making us spend days and days just to have it working it's unacceptable.

**Comment by torkvell** [comment]
Hi @joamafer ,

Sorry to hear the CocoaPods are not working for you. I've shared my own working project with you in your other ticket. I had no issues to build with CocoaPods. 

For the Carthage issue: We made a release yesterday which shall enable you all to move forward with your build: [https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v6.4.3-Xcode-11.2.1](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v6.4.3-Xcode-11.2.1)

Our SDK team will continue investigating why modular stability doesn't work for Carthage. Rest assured that full focus is given to this. 

As always, please let me know if there is anything else we can assist on.

**Comment by torkvell** [comment]
Hi all,

If you're running into a compilation versioning issue for Carthage e.g. ```Incompatible Swift version - framework was built with X1 and the local version is X2```, then try to delete your local cache folder ```org.carthage.CarthageKit``` and then do a new ```carthage update --platform iOS```.

![2019-11-25 at 14 54](https://user-images.githubusercontent.com/40064170/69546179-838ebb80-0f93-11ea-8b1b-23b0b73bada9.png)

I hope this helps. If there is anything else we can assist on then please let me know.

**Comment by cabaird** [comment]
Is there a Cocoapods version that's compatible with Xcode 11.2.1?  I've installed v6.4.3 with no luck.  Receiving Linker errors after updating to try and resolve the Swift compiler issues.

**Comment by torkvell** [comment]
Hi @cabaird,

v 6.4.3 is built with Xcode 11.2.1, so there should be no issue. To assist you with this please open a new ticket and specify the issue you're running into. Steps to reproduce and if you're making use of Cocoapods or Carthage. 

Looking forward to your reply.
