### ISSUE TITLE
Xcode 9 Support

### ISSUE THREAD

**Issue by packatino** [usabilla/usabilla-u4a-ios-swift-sdk#49]
It would be great if the Usabilla SDK would work with Xcode 9.

When I try to build my project with Xcode 9 I get the following error at the import statement for the UsabillaFeedbackForm:
```
Module compiled with Swift 3.1 cannot be imported in Swift 4.0
```

I also get this error message:
```
ld: /Users/.../Pods/UsabillaFeedbackForm/UsabillaFeedbackForm.framework/UsabillaFeedbackForm compiled with older version of Swift language (3.0) than previous files (unknown ABI version 0x05) file '/Users/.../Pods/UsabillaFeedbackForm/UsabillaFeedbackForm.framework/UsabillaFeedbackForm' for architecture x86_64
```

I guess building the Usabilla SDK with a compiler for Swift 3.2 would work. As far as I know the compiler in Xcode 9 understands both Swift 4 and Swift 3.2.

Usabilla is the only pod that blocks me from using the latest Xcode version. I know that Xcode 9 is still a beta but it would be so great if it was already possible to build the Usabilla SDK anyway :)

**Comment by gPinato** [comment]
Hi @packatino,
I understand your issue.

We will investigate this problem and come up with a solution that is best suitable for both of us.
I will keep you posted, it won't take long.

**Comment by packatino** [comment]
Thanks a lot! :)

**Comment by Daij-Djan** [comment]
Id need that to for your next development project

**Comment by diederikh** [comment]
Same here.

**Comment by gPinato** [comment]
Small update: we will release a version of our SDK compatible with Xcode 9 in the upcoming days.
I will let you know as soon as we publish it.

**Comment by diederikh** [comment]
@gPinato Does release 3.5.0 have the Xcode 9/Swift 3.2 support?

**Comment by tyten** [comment]
@diederikh Does not appear so

**Comment by gPinato** [comment]
A version in swift 3.2 of the SDK has been just released.
This is an exact copy of v3.6.0, only compiled in swift 3.2.   

You can find it in the `feature/swift3.2` branch.

You can use it your pod file with 
`pod 'UsabillaFeedbackForm', :git => 'https://github.com/usabilla/usabilla-u4a-ios-swift-sdk.git', :branch=> 'feature/swift3.2'`

Let me know if you experience any problem with it.

**Comment by packatino** [comment]
Thanks for your efforts! The new version is working with Xcode 9 :)

However, I cannot compile it with Xcode 8.3.3 anymore :( Even after cleaning the project and restarting Xcode. This is problematic because we still need Xcode 8 for building our app for the App Store. I always get this error when I try to import the UsabillaFeedbackForm in a Swift class:

```
Module compiled with Swift 4.0 cannot be imported in Swift 3.1
```
Are you sure that you compiled this version with Swift 3.2? Do you have any idea what I could do?

**Comment by gPinato** [comment]
[Swift 3.2 is not an actual version. It is how Xcode 9 (and the Swift 4 compiler) calls Swift 3](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Compatibility.html).
So it's normal that xcode 8 complains about Swift 4 code.

v3.6.0-swift3.2 is only compatible with xcode 9 and the swift 4 compiler.

To use xcode 8 you still have to rely on v3.6.0

These two versions are identical, except for the compiler used to build them.

**Comment by Daij-Djan** [comment]
Thank you!

**Comment by daveanderson** [comment]
With the following lines of code I am presently getting a compiler segmentation fault with Xcode version 9.0 beta 3 (9M174d)

```
        UsabillaFeedbackForm.delegate = self
        UsabillaFeedbackForm.loadFeedbackForm("5[...]7")
        UsabillaFeedbackForm.showCancelButton = true
```

```
2.	While type-checking expression at [File.swift:15:9 - line:15:41] RangeText="UsabillaFeedbackForm.delegate = s"
3.	While loading conformances for 'UsabillaFeedbackForm' in module 'UsabillaFeedbackForm'
4.	While reading conformance for type 'UsabillaFeedbackForm'
5.	While ... to 'AnyObject' in module 'Swift'
```

Please advise.

**Comment by daveanderson** [comment]
Does `v3.6.0-swift3.2` need to be rebuilt with the Xcode9b4?

**Comment by gPinato** [comment]
@daveanderson The framework was indeed causing a segmentation fault because it was not compiled with the latest beta.
I've pushed a version compiled with beta 4 on the branch, fetching it with cocoapod should fix all problems.

If by chance somebody still needs the beta 2 version, a commit can be specified in the pod line to select the older one.

**Comment by daveanderson** [comment]
Thank you for the quick turnaround.

**Comment by daveanderson** [comment]
Unfortunately I'm still getting the following error

```
File.swift:10:8: error: cannot load underlying module for 'UsabillaFeedbackForm'
import UsabillaFeedbackForm
       ^
```

My Podfile.lock indicates that I'm using the following commit

```
  UsabillaFeedbackForm:
    :commit: 4a1e8696431b5ea15ddfe6df35029a5412daa6cd
    :git: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk.git
```

**Comment by gPinato** [comment]
it works fine for me on both simulators and iphone.

**Comment by rolf-fox** [comment]
I am also having this issue with your Xcode9b4-compatible build.

![screen shot 2017-08-02 at 4 24 43 pm](https://user-images.githubusercontent.com/13002364/28898648-4000c298-77a4-11e7-9db1-81e5feed530f.png)

I have tried:
1) Cleaning the project and the derived data before each build
2) Restarting Xcode
3) Most of the fixes that are mentioned here: https://stackoverflow.com/questions/32673866/cocoapods-cannot-load-underlying-module-for-x, and here, https://github.com/Alamofire/Alamofire/issues/441 (because it seems to be a common problem with cocoapods)
4) I also tried removing Usabilla from the Podfile, and adding it manually to the project's embedded frameworks, but I still got the same error

**Comment by jingx23** [comment]
Seems that with the new Xcode9b5 the same problem occurs ```Module compiled with Swift 4.0 cannot be imported in Swift 3.2```.
Is there any solution that will work with all coming Xcode versions?

**Comment by gPinato** [comment]
I've recompiled the framework with Xcode 9 beta 5 and just pushed it on the branch. 
It's the latest commit.

I've tried it on a couple of different machines and project and it seems to work, let me know if you experience any problem with it.

**Comment by jingx23** [comment]
It works, thanks!

**Comment by daveanderson** [comment]
Latest commit is also working with me and Xcode 9 beta 5. Thank you.

We'll all be happier when we finally see _evidence_ of ABI stability actually shipping this time next year.

**Comment by edwinveger** [comment]
Right now, I'm including it through CocoaPods to my Swift 3.2 project (no time yet to migrate our codebase) by adding the following line to my Podfile:

`pod 'UsabillaFeedbackForm', :git => 'https://github.com/usabilla/usabilla-u4a-ios-swift-sdk', :commit => '340ad4eda3'`

I get the error `module compiled with Swift 4.0 cannot be imported in Swift 3.2`. I am using the "v3.6.0-swift3.2" release, am I not?

**Comment by Werewolve** [comment]
Is the release date already planned for the final Swift 4 / Xcode 9 compatible version?
Its really important for our next app release.

**Comment by diederikh** [comment]
+1

**Comment by Goseong** [comment]
@Werewolve @diederikh we will make a new release with the official release tomorrow.

**Comment by gPinato** [comment]
V3.6.1 of the SDK (the latest) has just been published on the Swift 3.2 branch, compiled with Xcode 9 GM.

This should be the final version of Xcode, so there should not be any problem.

**Comment by cikpis** [comment]
Hi @gPinato, I just check the new Xcode 9 with my project and I got that error in both "v3.6.1" and "v3.6.0-swift3.2-beta4".

Any clue why?

**Comment by gPinato** [comment]
@cikpis are you using 

`pod 'UsabillaFeedbackForm', :git => 'https://github.com/usabilla/usabilla-u4a-ios-swift-sdk.git', :branch=> 'feature/swift3.2'`

to fetch the pod?

**Comment by cikpis** [comment]
I'm using Carthage without specifying a tag.

**Comment by daveanderson** [comment]
Of note:

>>> And are you using any separately-compiled Swift modules? That still doesn't officially work IIUC.

https://twitter.com/jckarter/status/910622896791228416

**Comment by grimabe** [comment]
@cikpis I added the binary with a new tag for 3.6.1 with Xcode 9
You should now be able to fetch it with this in your Cartfile: 
`github "usabilla/usabilla-u4a-ios-swift-sdk" "v3.6.1-xcode9"`

**Comment by cikpis** [comment]
I used `github "usabilla/usabilla-u4a-ios-swift-sdk" "feature/swift3.2"` and it's working. I'll try with `github "usabilla/usabilla-u4a-ios-swift-sdk" "v3.6.1-xcode9"`, thanks!

BTW, why `UsabillaFeedbackForm.appStoreId` is not found anymore?

**Comment by grimabe** [comment]
Nice to hear it is working.
The redirect to appStore feature has been removed in 3.5.0 ([release note](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v3.5.0 ))


The information is also available in the [documentation](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#app-store-rating)

You can, therefore, use our recommended way with Apple native Rating Prompt.

**Comment by cikpis** [comment]
Oh snap! I have now to tell that to the PO :)

Anyway, I guess is better use `v3.6.1-xcode9` than `feature/swift3.2` right?

**Comment by grimabe** [comment]
Well, I'd rather use the tag than the branch indeed. 
Especially that in a near feature we might make Xcode 9 release on master and create a specific branch for supporting Xcode 8

**Comment by cikpis** [comment]
Yeah make sense.  I'm gonna try `feature/swift3.2` and i'll keep you posted.

Thanks for you time 👍 cheers!

**Comment by cikpis** [comment]
Seems there is a problem with the delegates. Please look at the attached image.

Basically in your declaration you have `[UsabillaFeedbackForm.FeedbackResult]` but if I implement in that way I got the attached error.

If I try to remove `UsabillaFeedbackForm` and leave just `[FeedbackResult]` there is not error anymore but that method of course is not called. Could you check it?

**Comment by gPinato** [comment]
`FeedbackResult` is not declared within `UsabillaFeedbackForm`, that signature cannot work.

The correct methods are these:
```
func formDidClose(_ form: UINavigationController, formID: String, with feedbackResults: [FeedbackResult], isRedirectToAppStoreEnabled: Bool)
func formWillClose(_ form: UINavigationController, formID: String, with feedbackResults: [FeedbackResult], isRedirectToAppStoreEnabled: Bool)
```


`formWillClose` should always be called, while `formDidClose` will only be called if `UsabillaFeedbackForm.dismissAutomatically` is set to `true`.

They work correclty for me, could you double check your implementation? Are you sure the delegate property is the correct one?

**Comment by cikpis** [comment]
Ah! Ok then. Before `formWillClose ` was called when `UsabillaFeedbackForm.dismissAutomatically` was set to `false`. I guess is that the problem. Let me check.

**Comment by cikpis** [comment]
@gPinato in `formWillClose` is called but seems that the `FeedbackResult` does not have a `sent` property.
 ```swift
(lldb) po feedbackResults.first
▿ Optional<FeedbackResult>
  ▿ some : FeedbackResult
    ▿ rating : Optional<Int>
      - some : 5
    - abandonedPageIndex : nil
```
But your model has it. Is that normal?

**Comment by gPinato** [comment]
Hey @cikpis ,

as stated in the readme
>The abandonedPageIndex is only set if the user cancels the form before submission.

so it's normal for it to be nil if the form was submitted.

Regarding the sent property, it is a computed property, so it will not be printed within a description but it is still accessible.

![image](https://user-images.githubusercontent.com/6040180/30773002-cc23e1d8-a067-11e7-84c2-e63df7e6b135.png)

**Comment by cikpis** [comment]
Make sense. Then why it is false even though the user voted?

**Comment by cikpis** [comment]
Hi @grimabe, does the `v3.6.1-xcode9` have support for swift 4?

**Comment by grimabe** [comment]
@cikpis `v3.6.1-xcode9` has been compiled with Xcode 9 and swift 3.2 so it is compatible with swift 4 as well. Also regarding your other concern please create another ticket so it does not notify all the watchers of this issue.

**Comment by cikpis** [comment]
@grimabe compiling for Swift 3.2 doesn't mean it is automatically working in Swift 4. But yes, I just tested and it is working :)

I'm gonna open another issue for the other one, cheers!
